### ISSUE TITLE
Planificar las pruebas unitarias

### ISSUE THREAD

**Issue by MarquezEmanuel** [EmilianoAguero/Emueble#10]
Se deben planificar las pruebas unitarias del proyecto para los siguientes casos de uso:

- Alta de mueble : Se debe almacenar en la base de datos el nuevo registro.
- Baja de mueble: Se debe eliminar el registro de la base de datos.
- Modificación de mueble: Se debe editar la información de un mueble existente en la base de datos.
- Búsqueda: Se debe observar el listado de muebles cargados en la base de datos.

**Comment by MarquezEmanuel** [comment]
Cada prueba tiene un objetivo específico:

•	La prueba de alta tiene como objetivo agregar un nuevo mueble a la base de datos y verificar que aparezca en la lista de muebles.
•	La prueba de baja tiene como objetivo eliminar un mueble existente y verificar que desaparezca de la lista de muebles y no se pueda modificar ni buscar.
•	La prueba de modificación tiene como objetivo cambiar los valores de un mueble existente y verificar que se guarden correctamente y se reflejen en la lista de muebles.
•	La prueba de búsqueda por nombre tiene como objetivo encontrar un mueble específico en la base de datos y comprobar que sus valores son correctos y que no aparecen otros muebles con nombres similares.

**Comment by MarquezEmanuel** [comment]
Se detallan los resultados esperados para cada prueba a continuación:
•	En la prueba de alta, esperamos que el nuevo mueble se añada correctamente a la base de datos y que sea visible en la lista de muebles.
•	En la prueba de baja, esperamos que el mueble seleccionado se elimine de la base de datos y deje de aparecer en la lista de muebles.
•	En la prueba de modificación, esperamos que los cambios realizados en el mueble se guarden correctamente y se reflejen en la lista de muebles.
•	En la prueba de búsqueda por nombre, esperamos encontrar el mueble especificado y comprobar que sus valores son correctos, y que no aparezcan otros muebles con nombres similares.

**Comment by MarquezEmanuel** [comment]
Se documentan las secciones correspondientes del informe

**Comment by MarquezEmanuel** [comment]
Se evaluaron con @Luvaanu los resultados obtenidos.
Se realizó la comparacion entre los resultados esperados y los obtenidos. Esto en apoyo con los asserts establecidos en PHP Unit

**Comment by Luvaanu** [comment]
Se ejecutaron las pruebas unitarias y se documento cada paso de las pruebas realizadas

**Comment by MarquezEmanuel** [comment]
Se finalizó la documentación.
