### ISSUE TITLE
Configurar PHP Unit y XDebug

### ISSUE THREAD

**Issue by MarquezEmanuel** [EmilianoAguero/Emueble#9]
Se debe realizar la instalación y configuración de las herramientas que se detallan:

- PHP Unit - Ultima versión disponible.
- XDebug - La correspondiente para la versión de XAMPP.

Verificar la instalación.

**Comment by MarquezEmanuel** [comment]
Se realiza una Reunión en forma virtual para realizar la instalación y configuración de los ambientes.

En dicha Reunión participaron:

@EmilianoAguero 
@Luvaanu 
@MarquezEmanuel

**Comment by MarquezEmanuel** [comment]
Para el caso de PHP Unit se debió:

- Configuración del composer.
- Ejecución de un test unitario de ejemplo.

Para XDegug se realizó:

Descarga de la DLL correspondiente.
Modificación del php.ini
 Verificación del PHP info.

**Comment by EmilianoAguero** [comment]
Realizado se creo un nuevo branch con la configuracion en base a composer necesaria "muble_xdebug_phpunit_psr"

**Comment by Luvaanu** [comment]
Se configuro en el entorno de prueba de cada participante y funciona correctamente se aprueba

**Comment by Luvaanu** [comment]
Se solicita aprobación del solicitante

**Comment by MarquezEmanuel** [comment]
Aprobado!
